Disable PythonTestSSLSocket since it fails for 3.4
- Test error: AttributeError: module 'ssl' has no attribute 'PROTOCOL_TLS_CLIENT'
  - in "thrift\transport\TSSLSocket.py", line 50, in TSSLBase"