THRIFT-5899: Python tests fail for the Appveyor MSVC builds (#3229)
* Temporarily switch off shared build

- See THRIFT-5898

* Skip type_hints tests for python lower than 3.7

- PR#2929 called out that the changes breaks Python 3.5 since types came in in 3.6
- Python 3.6 errors out with 'from __future__ import annotations' since it looks like it was only added in 3.7

* More appveyer issues on Windows due to old python

* Remove enum tests for old python versions

- Getting `raise TApplicationException(TApplicationException.MISSING_RESULT, "testEnum failed: unknown result"` error
- PR#2825 state it is a breaking change, not sure why and for what version of Python

* Disable SSL tests for old Python

- Appveyor error: ` AttributeError: module 'ssl' has no attribute 'PROTOCOL_TLS_CLIENT'`

* Can't get the test to skip so revert the change that broke it

- See PR#3050

* THRIFT-5900: Pin the cross test stage to python 3.13

- See https://issues.apache.org/jira/browse/THRIFT-5900