Fix travis CI for NPM
Currently it's complaining about missing dependency of headless chrome:

    Running "qunit:ThriftDeepConstructor" (qunit) task
    >> There was an error with headless chrome
    Fatal error: Failed to launch chrome!
    /thrift/src/lib/js/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory
    TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md